namespace TypeScriptGenerator
{
    public partial class CodeGenerator
    {
        public static readonly string EnumAsStringAttributeFullName = $"{CustomNamespace}.{EnumAsStringAttributeName}";
        private const string EnumAsStringAttributeName = "EnumAsStringAttribute";
        private static readonly string EnumAsStringAttributeText =
            $@"using System;
using System.Diagnostics.CodeAnalysis;

namespace {CustomNamespace}
{{
    [AttributeUsage(AttributeTargets.Enum)]
    [SuppressMessage(
        ""StyleCop.CSharp.DocumentationRules"",
        ""SA1649:File name must match first type name"",
        Justification = ""Autogenerated file."")]
    public class {EnumAsStringAttributeName}
       : Attribute
    {{
        public {EnumAsStringAttributeName}()
        {{
        }}
    }}
}}";
    }
}