namespace TypeScriptGenerator
{
    public partial class CodeGenerator
    {
        private const string CustomNameAttributeName = "CustomNameAttribute";
        private static readonly string CustomNameAttributeFullName = $"{CustomNamespace}.{CustomNameAttributeName}";
        private static readonly string CustomNameAttributeText =
            $@"using System;
using System.Diagnostics.CodeAnalysis;

namespace {CustomNamespace}
{{
    [AttributeUsage(AttributeTargets.Method)]
    [SuppressMessage(
        ""StyleCop.CSharp.DocumentationRules"",
        ""SA1649:File name must match first type name"",
        Justification = ""Autogenerated file."")]
    public class {CustomNameAttributeName}
       : Attribute
    {{
        public {CustomNameAttributeName}(string? name)
        {{
            Name = name;
        }}

        public string? Name {{ get; }}
    }}
}}";
    }
}