namespace TypeScriptGenerator
{
    public partial class CodeGenerator
    {
        public static readonly string EnumLabelAttributeFullName = $"{CustomNamespace}.{EnumLabelAttributeName}";
        private const string EnumLabelAttributeName = "EnumLabelAttribute";
        private static readonly string EnumLabelAttributeText =
            $@"using System;
using System.Diagnostics.CodeAnalysis;

namespace {CustomNamespace}
{{
    [AttributeUsage(AttributeTargets.Field)]
    [SuppressMessage(
        ""StyleCop.CSharp.DocumentationRules"",
        ""SA1649:File name must match first type name"",
        Justification = ""Autogenerated file."")]
    public class {EnumLabelAttributeName}
       : Attribute
    {{
        public {EnumLabelAttributeName}(string? text)
        {{
            Text = text;
        }}

        public string? Text {{ get; }}
    }}
}}";
    }
}