// Generated by https://github.com/AdaskoTheBeAsT/TypeScriptGenerator

import { EnumHelper } from './_enum-helper';

export enum Sample1 {
  First = 5,
  Second = 6,
}

export namespace Sample1 {

  export function getLabel(value: Sample1): string {
    switch(value) {
      case Sample1.First: return 'First';
      case Sample1.Second: return 'Second';
      default: throw new Error('Invalid value=`${value}`');
    }
  }

  export function getKeys(): string[] {
    return EnumHelper.getKeys(Sample1);  
  }

  export function getValues(): Sample1[] {
    return EnumHelper.getValues(Sample1);
  }


}

