// Generated by https://github.com/AdaskoTheBeAsT/TypeScriptGenerator

import { Material } from './Material';

export class Product {
  public id: number;
  public name: string;
  public material: any;
}
